### ISSUE TITLE
Update for 11.14 native_firm (?)

### ISSUE THREAD

**Issue by Ammako** [Ammako/CakesForeveryWan#1]
May need to be updated to support 11.14 native_firm. Not super interested in spending time on that right now, though, but it'll be done at some point.

For the time being, a 11.12 native_firm may work fine even on 11.14 firmware. It's unlikely that anything absolutely requires a 11.14 native_firm (games or otherwise), but I can't guarantee anything.

**Comment by thaikhoa** [comment]
Please, we need you. Thanks so much.

**Comment by Ammako** [comment]
Will look into it

**Comment by thaikhoa** [comment]
Can't wait. Hope it will be implemented soon. Cheers.

**Comment by Ammako** [comment]
I'm just trying to get build working again, it's a pain though and I don't know if I'll even be able to get that going again. But even if I can't build, I could at least still update the source, and all that would be left is to build it.

**Comment by ghost** [comment]
https://github.com/Ammako/CakesForeveryWan/releases/tag/210

**Comment by thaikhoa** [comment]
Thanks so much for the unexpected update.
A quick question, do you have any idea how to run NTR CFW on CakesFW?

Cheers.

**Comment by ghost** [comment]
Should work with svcBackdoor patch

https://github.com/Ammako/icing/blob/master/svcBackdoor.cake

**Comment by thaikhoa** [comment]
Which NTR CFW should I use for CakesFW?

**Comment by ghost** [comment]
Same as always

https://github.com/Nanquitas/BootNTR/releases

It doesn't work on Luma because they did something with their custom modules that ended up breaking compatibility, Cakes shouldn't have that issue though because it only does the bare minimum of modifications to get basic CFW functionality.

That being said I don't use NTR. In theory the svcBackdoor patch should be all you need, but I haven't tested it.
